language: rust
rust:
  - stable
  - beta
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - rustup component add clippy
script:
  # fail on warnings, test all features
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --all --verbose

